#66.Python program to demonstrate exception handling-3
try:
    print(x)
except NameError:
    print("Variable is not defined")
else:
    print("No exception occured")
    

    
    

